apiVersion: v1
kind: ServiceAccount
metadata:
  name: innovation-intelligence-sa
  namespace: innovation-intelligence
  annotations:
    iam.gke.io/gcp-service-account: innovation-intelligence-sa@prj-digital-financial-analysis.iam.gserviceaccount.com
